In [18]:
import numpy as np

# Generate sample arrays
N, K = 6, 3
NxK = np.random.rand(N, K) #GAMMA
print('-------------NxK---------------- \n',NxK)
NxD = np.random.rand(N, 2) #DATAPOINTS
print('-------------NxD---------------- \n', NxD)

# Reshape NxK array to have 3 dimensions: N x K x 1
NxK_transpose = np.transpose(NxK)
NxK_3D = NxK_transpose[:,:,np.newaxis]
print('-------------NxK_3D---------------- \n',NxK_3D)

# Multiply NxK_3D with NxD to get the result
result = NxK_3D * NxD
print('-------------result---------------- \n', result)

# Reshape result back to 2 dimensions: N x (K*D)
#result = result.reshape(N, K*2)

-------------NxK---------------- 
 [[0.81857661 0.67589106 0.97707566]
 [0.22623145 0.93678103 0.94186661]
 [0.35673096 0.73265523 0.40936713]
 [0.13902632 0.26230521 0.08247359]
 [0.87727745 0.74646322 0.74882838]
 [0.78164538 0.7625582  0.51322546]]
-------------NxD---------------- 
 [[0.06546933 0.17812313]
 [0.71737311 0.07119475]
 [0.19813981 0.79895675]
 [0.75816475 0.07523333]
 [0.94903415 0.05330772]
 [0.1353091  0.26814586]]
-------------NxK_3D---------------- 
 [[[0.81857661]
  [0.22623145]
  [0.35673096]
  [0.13902632]
  [0.87727745]
  [0.78164538]]

 [[0.67589106]
  [0.93678103]
  [0.73265523]
  [0.26230521]
  [0.74646322]
  [0.7625582 ]]

 [[0.97707566]
  [0.94186661]
  [0.40936713]
  [0.08247359]
  [0.74882838]
  [0.51322546]]]
-------------result---------------- 
 [[[0.05359166 0.14580743]
  [0.16229236 0.01610649]
  [0.0706826  0.2850126 ]
  [0.10540486 0.01045941]
  [0.83256626 0.04676566]
  [0.10576373 0.20959497]]

 [[0.04425013 0.12039183]
  [0.67202152 0.06669389]


In [25]:
np.sum(result, axis=1)

array([[1.33030147, 0.71374657],
       [1.87191054, 1.03644874],
       [1.66338654, 0.75190474]])